import { test, expect, BrowserContext, Page, Browser } from '@playwright/test';
import { log } from './utils/logger';
import {
  MOCK_SERVER_URL,
  setupTestEnvironment,
  teardownTestEnvironment,
  resetMockServer,
  addMockMessage,
  disconnectAndInitialize,
} from './utils/test-helpers';

/**
 * E2E tests for Timestamp Timezone Display
 *
 * Verifies that chat message timestamps are displayed in the user's local timezone,
 * not in UTC. This is a critical usability feature for users in different timezones.
 *
 * Test Strategy:
 * 1. Send a message with a known timestamp (via mock server)
 * 2. Verify the displayed time matches the local timezone conversion
 *
 * Run tests:
 *    pnpm exec playwright test --config e2e-tauri/playwright.config.ts timestamp-timezone.spec.ts
 */

// Helper to add message with specific timestamp to mock server
async function addMockMessageWithTimestamp(message: {
  message_type: string;
  author: string;
  content: string;
  channel_id?: string;
  is_member?: boolean;
  timestamp_usec?: string;  // Optional: specific timestamp in microseconds
}): Promise<void> {
  await addMockMessage(message);
}

test.describe('Timestamp Timezone Display', () => {
  let browser: Browser;
  let context: BrowserContext;
  let mainPage: Page;

  test.beforeAll(async () => {
    test.setTimeout(240000); // 4 minutes for setup

    log.info('Setting up test environment for Timestamp Timezone Display tests...');
    const connection = await setupTestEnvironment();
    browser = connection.browser;
    context = connection.context;
    mainPage = connection.page;
    log.info('Connected to Tauri app');
  });

  test.afterAll(async () => {
    await teardownTestEnvironment(browser);
  });

  test.beforeEach(async () => {
    // Reset mock server before each test
    await resetMockServer();
  });

  test('should display message timestamp in local timezone, not UTC', async () => {
    // This test verifies that timestamps are displayed in the user's local timezone.
    //
    // The bug: Backend formats timestamp using chrono::DateTime::from_timestamp()
    // which creates UTC DateTime, then formats it as HH:MM:SS without timezone conversion.
    // This causes the displayed time to be in UTC instead of local timezone.
    //
    // Expected behavior: If a message arrives at 19:00 JST (10:00 UTC),
    // the displayed time should be "19:00:00", not "10:00:00".

    // Enable timestamp display
    const timestampToggle = mainPage.locator('label:has-text("タイムスタンプ") input[type="checkbox"]');
    if (!(await timestampToggle.isChecked())) {
      await timestampToggle.check();
    }

    // Connect to stream
    const urlInput = mainPage.locator('input[placeholder*="youtube.com"]');
    await urlInput.fill(`${MOCK_SERVER_URL}/watch?v=test_video_123`);
    await mainPage.locator('button:has-text("開始")').click();
    await expect(mainPage.getByText('Mock Live').first()).toBeVisible({ timeout: 10000 });

    // Record the current local time BEFORE adding the message
    const localTimeBeforeMs = Date.now();

    // Add a message (timestamp will be generated by mock server using current time)
    await addMockMessageWithTimestamp({
      message_type: 'text',
      author: 'TimezoneTestUser',
      content: 'Testing timezone display',
    });

    // Wait for message to appear
    await mainPage.waitForTimeout(3000);

    // Verify message is displayed
    await expect(mainPage.locator('text=TimezoneTestUser')).toBeVisible();
    await expect(mainPage.locator('text=Testing timezone display')).toBeVisible();

    // Get the displayed timestamp from the UI
    // The timestamp is in HH:MM:SS format next to the message
    const messageElement = mainPage.locator('[data-message-id]').filter({
      has: mainPage.locator('text=TimezoneTestUser')
    }).first();

    // Find the timestamp element (HH:MM:SS format)
    const timestampElement = messageElement.locator('span').filter({
      hasText: /^\d{2}:\d{2}:\d{2}$/
    }).first();

    await expect(timestampElement).toBeVisible();
    const displayedTime = await timestampElement.textContent();
    log.debug(`Displayed timestamp: ${displayedTime}`);

    // Parse the displayed time
    const [displayedHours, displayedMinutes] = displayedTime!.split(':').map(Number);

    // Calculate expected local time (what the time should be in user's timezone)
    const localTime = new Date(localTimeBeforeMs);
    const expectedLocalHours = localTime.getHours();
    const expectedLocalMinutes = localTime.getMinutes();

    // Calculate UTC time (what the bug would show)
    const utcHours = localTime.getUTCHours();
    const utcMinutes = localTime.getUTCMinutes();

    log.debug(`Expected local time: ${expectedLocalHours.toString().padStart(2, '0')}:${expectedLocalMinutes.toString().padStart(2, '0')}`);
    log.debug(`UTC time (bug would show): ${utcHours.toString().padStart(2, '0')}:${utcMinutes.toString().padStart(2, '0')}`);
    log.debug(`Timezone offset: ${localTime.getTimezoneOffset()} minutes (${-localTime.getTimezoneOffset() / 60} hours from UTC)`);

    // Allow ±2 minutes tolerance for test execution time
    const isWithinLocalTimeRange = (
      Math.abs(displayedHours - expectedLocalHours) <= 0 ||
      // Handle day boundary (23:59 -> 00:01)
      (expectedLocalHours === 23 && displayedHours === 0) ||
      (expectedLocalHours === 0 && displayedHours === 23)
    ) && Math.abs(displayedMinutes - expectedLocalMinutes) <= 2;

    // Check if displayed time matches UTC (the bug)
    const isMatchingUTC = (
      Math.abs(displayedHours - utcHours) <= 0 ||
      (utcHours === 23 && displayedHours === 0) ||
      (utcHours === 0 && displayedHours === 23)
    ) && Math.abs(displayedMinutes - utcMinutes) <= 2;

    // If timezone offset is 0 (UTC), skip this test as it can't detect the bug
    if (localTime.getTimezoneOffset() === 0) {
      log.info('Skipping timezone test: system timezone is UTC, cannot detect UTC vs local bug');
      // Disconnect and return
      await disconnectAndInitialize(mainPage);
      return;
    }

    // The timestamp SHOULD match local time, NOT UTC
    // If it matches UTC but not local time, the bug is present
    if (isMatchingUTC && !isWithinLocalTimeRange) {
      // This is the bug we're testing for!
      throw new Error(
        `Timestamp is displayed in UTC instead of local timezone!\n` +
        `  Displayed: ${displayedTime}\n` +
        `  Expected (local): ${expectedLocalHours.toString().padStart(2, '0')}:${expectedLocalMinutes.toString().padStart(2, '0')}:xx\n` +
        `  Bug shows (UTC): ${utcHours.toString().padStart(2, '0')}:${utcMinutes.toString().padStart(2, '0')}:xx\n` +
        `  Timezone offset: ${-localTime.getTimezoneOffset() / 60} hours from UTC`
      );
    }

    // Assert that timestamp matches local time
    expect(isWithinLocalTimeRange).toBeTruthy();

    // Disconnect
    await disconnectAndInitialize(mainPage);
  });

  test('should display consistent timestamps across multiple messages', async () => {
    // This test verifies that all messages use the same timezone (local)

    // Enable timestamp display
    const timestampToggle = mainPage.locator('label:has-text("タイムスタンプ") input[type="checkbox"]');
    if (!(await timestampToggle.isChecked())) {
      await timestampToggle.check();
    }

    // Connect to stream
    const urlInput = mainPage.locator('input[placeholder*="youtube.com"]');
    await urlInput.fill(`${MOCK_SERVER_URL}/watch?v=test_video_123`);
    await mainPage.locator('button:has-text("開始")').click();
    await expect(mainPage.getByText('Mock Live').first()).toBeVisible({ timeout: 10000 });

    // Add multiple messages with short delays
    for (let i = 1; i <= 3; i++) {
      await addMockMessageWithTimestamp({
        message_type: 'text',
        author: `ConsistencyUser${i}`,
        content: `Consistency test message ${i}`,
      });
      await mainPage.waitForTimeout(500);
    }

    // Wait for all messages
    await mainPage.waitForTimeout(3000);

    // Get all displayed timestamps
    const timestamps: string[] = [];
    for (let i = 1; i <= 3; i++) {
      const messageElement = mainPage.locator('[data-message-id]').filter({
        has: mainPage.locator(`text=ConsistencyUser${i}`)
      }).first();

      const timestampElement = messageElement.locator('span').filter({
        hasText: /^\d{2}:\d{2}:\d{2}$/
      }).first();

      if (await timestampElement.isVisible()) {
        const ts = await timestampElement.textContent();
        if (ts) timestamps.push(ts);
      }
    }

    log.debug(`Collected timestamps: ${timestamps.join(', ')}`);

    // All timestamps should have the same hour (unless crossing hour boundary)
    // This verifies they're all using the same timezone
    if (timestamps.length >= 2) {
      const hours = timestamps.map(ts => parseInt(ts.split(':')[0]));
      const firstHour = hours[0];

      // Allow for hour boundary crossing (e.g., 23 -> 00)
      const allSameTimezone = hours.every(h =>
        h === firstHour ||
        Math.abs(h - firstHour) === 1 ||
        (firstHour === 23 && h === 0) ||
        (firstHour === 0 && h === 23)
      );

      expect(allSameTimezone).toBeTruthy();
    }

    // Disconnect
    await disconnectAndInitialize(mainPage);
  });
});
